import test from 'node:test';
import assert from 'node:assert/strict';
import { Game, LEVELS, CARDS, count } from '../src/engine.js';

function quiet(options={}) { const g=new Game({seed:73129,opponents:3,...options});g.factions.forEach(f=>f.nextThink=Infinity);return g; }
function advance(g,seconds){for(let i=0;i<Math.round(seconds/.05);i++)g.step(.05);}
function give(g,owner,key){g.factions[owner].hand=[key];g.factions[owner].globalCD=0;g.factions[owner].cooldowns[key]=0;}
test('all map sizes are connected with unique legal starts',()=>{for(const size of ['small','medium','large'])for(const opponents of [1,2,3]){const g=quiet({size,opponents}),seen=new Set([0]),open=[0];while(open.length)for(const x of g.adj[open.pop()])if(!seen.has(x)){seen.add(x);open.push(x);}assert.equal(seen.size,g.nodes.length);for(const f of g.factions){assert.equal(g.owned(f.id).length,1);assert.equal(count(g.owned(f.id)[0]),10);}g.assertValid();}});
test('exact level production, hard cap, no stored production at cap',()=>{for(const level of [1,2,3]){const g=quiet(),n=g.owned(0)[0];n.level=level;n.hp=LEVELS[level].hp;n.power=8;advance(g,3);assert.equal(count(n),2+level);n.power=LEVELS[level].cap*4;advance(g,12);n.power-=8;advance(g,2.9);assert.equal(count(n),LEVELS[level].cap-2);advance(g,.1);assert.equal(count(n),Math.min(LEVELS[level].cap,LEVELS[level].cap-2+level));}});
test('dispatch preserves two defenders and rejects blocked routes',()=>{const g=quiet(),n=g.owned(0)[0],target=g.adj[n.id][0];assert.equal(g.send(0,n.id,target,1).amount,8);assert.equal(count(n),2);assert.equal(g.send(0,n.id,target).ok,false);assert.equal(g.send(0,n.id,2).ok,false);g.assertValid();});
test('friendly multihop route stops at an intermediate city that changes owner',()=>{const g=quiet(),n=g.nodes[9];g.nodes[10].owner=0;g.nodes[10].power=8;assert(g.send(0,9,11,.5).ok);g.nodes[10].owner=1;g.step(.05);assert.deepEqual(g.armies[0].path,[9,10]);assert.equal(g.armies[0].target,10);});
test('seven versus five leaves two survivors occupying with 50% durability',()=>{const g=quiet(),n=g.nodes[4];n.owner=1;n.power=20;n.hp=100;n.attackers=[{owner:0,power:28}];g.battle(n);g.battle(n);assert.equal(n.owner,0);assert.equal(count(n),2);assert.equal(n.hp,50);});
test('wall reaches zero in a simultaneous wipe: surviving defenders rout to neutral ruins',()=>{const g=quiet(),n=g.nodes[4];n.owner=1;n.power=40;n.hp=40;n.attackers=[{owner:0,power:24}];g.battle(n);assert.equal(n.hp,10);g.battle(n);assert.equal(n.owner,-1);assert.equal(n.power,0);assert.equal(n.hp,0);assert.equal(g.factions[0].kills,6);});
test('equal soldiers without breached wall keep original zero-garrison ownership',()=>{const g=quiet(),n=g.nodes[4];n.owner=1;n.power=12;n.hp=100;n.attackers=[{owner:0,power:12}];g.battle(n);assert.equal(n.owner,1);assert.equal(n.power,0);assert.equal(n.hp,70);});
test('three simultaneous attackers resolve to a single owner or ruins, never multiple owners',()=>{const g=quiet(),n=g.nodes[4];n.owner=1;n.power=4;n.hp=20;n.attackers=[{owner:0,power:20},{owner:2,power:12},{owner:3,power:8}];for(let i=0;i<10;i++)g.battle(n);assert.equal(n.attackers.length,0);assert(n.owner===0||n.owner===2||n.owner===3||n.owner===-1);g.assertValid();});
test('upgrades consume troops, freeze production, preserve durability ratio and improve stats',()=>{const g=quiet(),n=g.owned(0)[0];n.hp=50;n.lastHit=0;assert(g.upgrade(0,n.id).ok);assert.equal(count(n),2);advance(g,4);assert.equal(n.level,2);assert.equal(n.hp,90);assert.equal(count(n),2);advance(g,3);assert.equal(count(n),4);});
test('attacked upgrades pause, ownership change cancels them',()=>{const g=quiet(),n=g.owned(0)[0];g.upgrade(0,n.id);n.attackers=[{owner:1,power:120}];const remaining=n.upgrade.remaining;g.step(.1);assert.equal(n.upgrade.remaining,remaining);g.battle(n);assert.equal(n.owner,1);assert.equal(n.upgrade,null);});
test('recruit, capacity, shared cooldown, invalid target is free',()=>{const g=quiet(),n=g.owned(0)[0];give(g,0,'recruit');assert.equal(g.playCard(0,'recruit',g.owned(1)[0].id).ok,false);assert.deepEqual(g.factions[0].hand,['recruit']);assert.equal(g.playCard(0,'recruit',n.id).ok,false);n.power=8;assert(g.playCard(0,'recruit',n.id).ok);assert.equal(count(n),12);assert.equal(g.factions[0].hand.length,0);g.factions[0].hand.push('recruit');n.power=8;advance(g,1);assert.equal(g.playCard(0,'recruit',n.id).ok,false);assert.equal(g.factions[0].cooldowns.recruit,45);});
test('haste increases real movement speed without modifying combat or production',()=>{const g=quiet(),n=g.owned(0)[0];g.send(0,n.id,g.adj[n.id][0],.5);give(g,0,'haste');g.playCard(0,'haste',null);advance(g,1);assert(Math.abs(g.armies[0].progress-1.7/g.edgeTime(n.id,g.adj[n.id][0]))<.00001);});
test('guard absorbs wall damage and retains fractional troop damage',()=>{const g=quiet(),n=g.owned(0)[0];give(g,0,'guard');g.playCard(0,'guard',n.id);n.attackers=[{owner:1,power:40}];g.battle(n);assert.equal(n.hp,100);assert.equal(n.shield,10);assert.equal(n.attackers[0].power,25);assert.equal(count(n.attackers[0]),7);advance(g,11);assert.equal(n.shield,0);});
test('ink can break a city remotely, routes remaining guards but cannot capture',()=>{const g=quiet(),n=g.owned(1)[0];n.power=24;n.hp=40;give(g,0,'ink');assert(g.playCard(0,'ink',n.id).ok);assert.equal(n.owner,-1);assert.equal(n.hp,0);assert.equal(n.power,0);assert.equal(g.factions[0].kills,4);g.step(.05);assert.equal(g.factions[1].alive,false);});
test('aid adds six actual soldiers, repairs thirty, clips both caps',()=>{const g=quiet(),n=g.owned(0)[0];n.power=8;n.hp=50;give(g,0,'aid');g.playCard(0,'aid',n.id);assert.equal(count(n),8);assert.equal(n.hp,80);});
test('silence freezes existing production progress and clears on capture',()=>{const g=quiet(),n=g.owned(1)[0];n.power=8;n.prod=2;give(g,0,'silence');g.playCard(0,'silence',n.id);advance(g,8.9);assert.equal(n.prod,2);assert.equal(count(n),2);advance(g,1.1);assert.equal(count(n),3);n.silenceUntil=100;g.capture(n,{owner:0,power:8});assert.equal(n.silenceUntil,0);});
test('decoy attracts a real, limited response then expires without troop loss',()=>{const g=quiet(),enemy=g.owned(1)[0];enemy.power=48;const edge=g.edges.findIndex(([a,b])=>a===enemy.id||b===enemy.id);give(g,0,'decoy');assert(g.playCard(0,'decoy',{edge,t:.5}).ok);g.think(g.factions[1]);assert.equal(g.stats.ghostResponses,1);assert.equal(g.armies.filter(a=>a.ghostId).length,1);g.think(g.factions[1]);assert.equal(g.stats.ghostResponses,1);advance(g,9);assert.equal(g.ghosts.length,0);assert(g.armies.every(a=>!a.ghostId));g.assertValid();});
test('hands stop at five, deterministic seven-card bag, no phantom kills',()=>{const g=quiet();g.factions[0].hand=[];const all=[];for(let i=0;i<7;i++){g.drawCard(0);all.push(g.factions[0].hand.pop());}assert.equal(new Set(all).size,7);for(let i=0;i<10;i++)g.drawCard(0);assert.equal(g.factions[0].hand.length,5);});
test('last-city elimination removes marching armies and prevents late comeback',()=>{const g=quiet(),n=g.owned(1)[0];g.send(1,n.id,g.adj[n.id][0],.5);g.capture(n,{owner:0,power:8});g.checkEnd();assert.equal(g.factions[1].alive,false);assert(!g.armies.some(a=>a.owner===1));assert.equal(g.playCard(1,'haste',null).ok,false);});
test('owning enemy cities is not victory until all neutral cities are occupied',()=>{const g=quiet();for(const n of g.nodes)if(n.owner>0)n.owner=0;g.checkEnd();assert.equal(g.status,'playing');for(const n of g.nodes)n.owner=0;g.checkEnd();assert.equal(g.status,'victory');});
test('same seed and same action schedule reproduce an identical game',()=>{const a=new Game({seed:312,autoPlayer:true}),b=new Game({seed:312,autoPlayer:true});for(let i=0;i<2000;i++){a.step(.1);b.step(.1);}assert.deepEqual(a.nodes,b.nodes);assert.deepEqual(a.factions,b.factions);assert.deepEqual(a.stats,b.stats);});
